#Includes calls to ALL the packages that you use for your project, as well as output of the function sessionInfo()

# include all R packages in your project
library(devtools)
library(knitr)
library(rmarkdown)
library(xtable)
library(ggplot2)
library(glmnet)
library(lars)
library(MASS)
library(pls)
library(reshape2)
library(Matrix)
library(testthat)
sink("../../session_info.txt", append = TRUE)
cat("Session Information\n\n")
print(sessionInfo())
devtools::session_info()
sink()
print("completed")

